export enum Province {
  ON = 1,
  AB = 2,
  BC = 3,
  MB = 4,
  NB = 5,
  NL = 6,
  NT = 7,
  NS = 8,
  NU = 9,
  PE = 10,
  QC = 11,
  SK = 12,
  YT = 13,
}

export const provinceLabels: Record<Province, string> = {
  [Province.ON]: 'ON',
  [Province.AB]: 'AB',
  [Province.BC]: 'BC',
  [Province.MB]: 'MB',
  [Province.NB]: 'NB',
  [Province.NL]: 'NL',
  [Province.NT]: 'NT',
  [Province.NS]: 'NS',
  [Province.NU]: 'NU',
  [Province.PE]: 'PE',
  [Province.QC]: 'QC',
  [Province.SK]: 'SK',
  [Province.YT]: 'YT',
};