services:
  mfa-membership-database:
    image: postgres
    container_name: mfa-membership-database
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
  mfa-api:
    image: mfa/api
    container_name: mfa-api
    build: ./api/MfaApi
    ports:
      - 8000:8080
    links:
      - mfa-membership-database
    environment:
      - ASPNETCORE_ENVIRONMENT=
      - PGSQL_CONNECTION_STRING=
      - AUTH0_AUTHORITY=
      - AUTHO_AUDIENCE=
  mfa-admin-dashboard:
    image: mfa/admin-dashboard
    container_name: mfa-admin-dashboard
    build: ./dashboard
    ports:
      - 3000:80
    links:
      - mfa-api
    environment:
      - NEXT_PUBLIC_MFA_API_URL=
      - AUTH0_SECRET=
      - AUTH0_BASE_URL=
      - AUTH0_ISSUER_BASE_URL=
      - AUTH0_CLIENT_ID=
      - AUTH0_CLIENT_SECRET=
      - AUTH0_AUDIENCE=
volumes:
  secrets: