services:
  db:
    image: postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mfa
      POSTGRES_USER: mfa
      POSTGRES_DB: mfa
    ports:
      - 5432:5432
  api:
    image: mfa/api
    build: ./api/MfaApi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__postgresdb: Server=db;Port=5432;Database=mfa;TrustServerCertificate=true;
      Auth0__Authority: /run/secrets/auth0_authority
      Auth0__Audience: /run/secrets/auth0_audience
    secrets:
      - auth0_authority
      - auth0_audience
    ports:
      - 8000:8080
    depends_on:
      - db   
  dashboard:
    image: mfa/admin-dashboard
    build: ./dashboard
    environment:
      NEXT_PUBLIC_MFA_API_URL: http://api:8080/api
      AUTH0_BASE_URL: http://dashboard:3000
      AUTH0_ISSUER_BASE_URL: /run/secrets/auth0_authority
      AUTH0_CLIENT_ID: /run/secrets/auth0_client_id
      AUTH0_CLIENT_SECRET: /run/secrets/auth0_client_secret
      AUTH0_AUDIENCE: /run/secrets/auth0_audience
    secrets:
      - auth0_authority
      - auth0_client_id
      - auth0_client_secret
      - auth0_audience
    ports:
      - 3000:3000
    depends_on:
      - api
secrets:
  auth0_authority:
    environment: AUTH0_AUTHORITY
  auth0_audience:
    environment: AUTH0_AUDIENCE
  auth0_client_secret:
    environment: AUTH0_CLIENT_SECRET
  auth0_client_id:
    environment: AUTH0_CLIENT_ID