services:
  dashboard:
    image: mfa/admin-dashboard
    build: ./dashboard
    profiles: []
  backend:
    image: mfa/api
    build: ./api/MfaApi
    profiles: []
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
  secrets:
    image: hashicorp/vault:latest
    container_name: vault
    volumes:
      - ./secrets:/secrets
    ports:
      - 8200:8200

volumes:
  secrets: